// Code generated by protoc-gen-go. DO NOT EDIT.
// source: journal.proto

package pb // import "mdahlbom/google-photos-uploader/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Journal struct {
	// List of files / subdirectories
	Entries              []*JournalEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Journal) Reset()         { *m = Journal{} }
func (m *Journal) String() string { return proto.CompactTextString(m) }
func (*Journal) ProtoMessage()    {}
func (*Journal) Descriptor() ([]byte, []int) {
	return fileDescriptor_journal_4921eae3c61d77ac, []int{0}
}
func (m *Journal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Journal.Unmarshal(m, b)
}
func (m *Journal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Journal.Marshal(b, m, deterministic)
}
func (dst *Journal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Journal.Merge(dst, src)
}
func (m *Journal) XXX_Size() int {
	return xxx_messageInfo_Journal.Size(m)
}
func (m *Journal) XXX_DiscardUnknown() {
	xxx_messageInfo_Journal.DiscardUnknown(m)
}

var xxx_messageInfo_Journal proto.InternalMessageInfo

func (m *Journal) GetEntries() []*JournalEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type JournalEntry struct {
	// Name (relative) of the file or directory
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Upload token for this journal entry
	UploadToken string `protobuf:"bytes,2,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	// Whether this a 'media item' has been successfully created for this entry.
	// This also means the photo has been added to an album.
	MediaItemCreated     bool     `protobuf:"varint,3,opt,name=media_item_created,json=mediaItemCreated,proto3" json:"media_item_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JournalEntry) Reset()         { *m = JournalEntry{} }
func (m *JournalEntry) String() string { return proto.CompactTextString(m) }
func (*JournalEntry) ProtoMessage()    {}
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_journal_4921eae3c61d77ac, []int{1}
}
func (m *JournalEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalEntry.Unmarshal(m, b)
}
func (m *JournalEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalEntry.Marshal(b, m, deterministic)
}
func (dst *JournalEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalEntry.Merge(dst, src)
}
func (m *JournalEntry) XXX_Size() int {
	return xxx_messageInfo_JournalEntry.Size(m)
}
func (m *JournalEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalEntry.DiscardUnknown(m)
}

var xxx_messageInfo_JournalEntry proto.InternalMessageInfo

func (m *JournalEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JournalEntry) GetUploadToken() string {
	if m != nil {
		return m.UploadToken
	}
	return ""
}

func (m *JournalEntry) GetMediaItemCreated() bool {
	if m != nil {
		return m.MediaItemCreated
	}
	return false
}

func init() {
	proto.RegisterType((*Journal)(nil), "uploader.Journal")
	proto.RegisterType((*JournalEntry)(nil), "uploader.JournalEntry")
}

func init() { proto.RegisterFile("journal.proto", fileDescriptor_journal_4921eae3c61d77ac) }

var fileDescriptor_journal_4921eae3c61d77ac = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
	0x10, 0x80, 0x89, 0x4f, 0x7c, 0xcf, 0xb4, 0x82, 0x64, 0x90, 0x8c, 0xb5, 0x38, 0x74, 0xb0, 0xad,
	0xe8, 0xe8, 0xa6, 0x38, 0xe8, 0x58, 0x9c, 0x5c, 0x4a, 0x6a, 0x8e, 0xb6, 0x9a, 0xe4, 0x42, 0x7a,
	0x1d, 0xfc, 0xf7, 0x62, 0x62, 0xe1, 0x6d, 0xc7, 0xf7, 0x7d, 0x1c, 0x77, 0xfc, 0xe2, 0x0b, 0xd7,
	0xe0, 0x94, 0x69, 0x7c, 0x40, 0x42, 0x71, 0x58, 0xbd, 0x41, 0xa5, 0x21, 0x94, 0x8f, 0x7c, 0xff,
	0x96, 0x94, 0xb8, 0xe3, 0x7b, 0x70, 0x14, 0x66, 0x58, 0x24, 0x2b, 0x76, 0x55, 0x76, 0x7f, 0xd5,
	0x6c, 0x59, 0xf3, 0xdf, 0xbc, 0x38, 0x0a, 0x3f, 0xdd, 0x96, 0x95, 0x0b, 0xcf, 0x8f, 0x85, 0x10,
	0xfc, 0xd4, 0x29, 0x0b, 0x92, 0x15, 0xac, 0x3a, 0xef, 0xe2, 0x2c, 0xae, 0x79, 0x9e, 0xb6, 0xf4,
	0x84, 0xdf, 0xe0, 0xe4, 0x49, 0x74, 0x59, 0x62, 0xef, 0x7f, 0x48, 0xdc, 0x72, 0x61, 0x41, 0xcf,
	0xaa, 0x9f, 0x09, 0x6c, 0xff, 0x19, 0x40, 0x11, 0x68, 0xb9, 0x2b, 0x58, 0x75, 0xe8, 0x2e, 0xa3,
	0x79, 0x25, 0xb0, 0xcf, 0x89, 0x3f, 0xdd, 0x7c, 0x94, 0x56, 0xab, 0xc9, 0x0c, 0x68, 0xdb, 0x11,
	0x71, 0x34, 0x50, 0xfb, 0x09, 0x09, 0x97, 0x7a, 0xbb, 0xb6, 0xf5, 0xc3, 0x70, 0x16, 0x1f, 0x7d,
	0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x67, 0x33, 0x62, 0x0d, 0xf9, 0x00, 0x00, 0x00,
}
